version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6380:6379"  # Avoid port conflict if 6379 is already in use

